### ISSUE TITLE
fix kernel launch failures when grid dims are too large

### ISSUE THREAD

**Issue by bd4** [wdmapp/gtensor#154]
gtensor currently uses a fixed block size for CUDA/HIP kernels, which fails for arrays that are too large in a certain dimension (but still easily small enough to fit in a single kernel launch with a block size adjustment). This could be handled by a generic flattening n-d implementation (using 1d indexing), similar to the SYCL backend n-d assign/launch implementations, or with more complex logic to determine block and grid sizes.

**Comment by td-mpcdf** [comment]
This would be great as I am running into problems with large problems.

**Comment by bd4** [comment]
I can think of two strategies to handle this:

1. always use a N-d kernel that flattens to 1d with a fixed block size (like the SYCL N-d, N>3 implementation)
2. query the GPU API for max grid dimensions (could be cached in a static local var), and forward to the N-d kernel if the requested sizes don't fit. Less possibility for changing performance characteristics of existing code. 

@germasch what do you think? I am leaning towards (2).

**Comment by bd4** [comment]
Discussed out of band, decided to try (1) and test for performance regressions, keep it simple if possible.

**Comment by td-mpcdf** [comment]
I tried to add a test to run into the problem, but the test passes?! I do not understand why. So what I added in `test_assign.cxx` was
~~~
TEST(assign, device_gtensor_large_2d)
{
  gt::gtensor_device<int, 2> a(gt::shape(2, 17920000));
  gt::gtensor_device<int, 2> b(a.shape());
  gt::gtensor<int, 2> h_a(a.shape());
  gt::gtensor<int, 2> h_b(a.shape());

  int* adata = h_a.data();

  for (int i = 0; i < a.size(); i++) {
    adata[i] = i;
  }

  gt::copy(h_a, a);
  //assign(b,a);
  b = a;
  gt::copy(b, h_b);

  EXPECT_EQ(h_a, h_b);
}
~~~
The second dimension is clearly too large (even if divided by BS_Y=16) this is larger than 2^16-1 and should fail if it somewhere calls a kernel with these dimensions. But it does not. Only if I replace the `b=a` line by `assign(b,a)`, I run into the expected problems. Can you briefly explain, why it passes in the first case?

**Comment by bd4** [comment]
That is indeed strange. My guess is that the gcontainer family of objects, including gtensor, have the default generated copy assignment operator, and that is being called here instead of assign. Which should actually do the right thing for host gtensor object, not immediately obvious how it does the right thing for device objects. I guess the copy assignment operators of the underlying thrust::device_vector or gt::gtensor_storage objects are called and they do the right thing. I will investigate further, thanks for writing a test!

In general, I think some refinement is needed handling assignment in gtensor - I see some storage copies where they are not necessary, and some places where there may be an unnecessary resize of the lhs.

**Comment by bd4** [comment]
See WIP pr #159
