### ISSUE TITLE
gtblas: Inconsistent stream in C API when using getrs / getrs_banded

### ISSUE THREAD

**Issue by uphoffc** [wdmapp/gtensor#186]
I noticed that gtblas_Xgetrs_batched submits to the stream set with gtblas_set_stream but gtblas_banded_Xgetrs_batched always submits to the default stream. If one where to replace getrs_batched with getrs_banded_batched in a code which sets a non-default stream via gtblas_set_stream then one gets a race condition.
Hence, I would modify the getrs_banded_batched function to use the stream set by gtblas_set_stream. Do you agree or is getrs_banded submitting to the default stream a design decision?

**Comment by bd4** [comment]
The stream API is also inconsistent, between gt-blas and the rest of gtensor (the former predated general stream support). Adapting gt-blas to use the same interface is probably the best approach here.

**Comment by bd4** [comment]
For the C-API, this probably requires create_stream_view, destroy_stream_view, create_stream, destroy_stream for Fortran interop

**Comment by bd4** [comment]
@uphoffc this is addressed in #188

**Comment by uphoffc** [comment]
That was quick, thanks :-) #188 lgtm

**Comment by bd4** [comment]
closed by #188
