### ISSUE TITLE
hip: thrust backend does asynchronous array zeroing on gtensor construct

### ISSUE THREAD

**Issue by bd4** [wdmapp/gtensor#190]
rocThrust `device_vector` does an uninitialized fill (zeroes the data) asynchronously, so when a gtensor object is created with the thrust backend enabled (GTENSOR_USE_THRUST=ON), the data copied to the vector can be overwritten by the asynchronously running zeroing kernel. This differs from the behavior of recent CUDA thrust implementations, where it appears to be synchronous.

If we plan on keeping the thrust backend, perhaps we should add a condition synchronize in the constructor when using HIP and thrust backend?

**Comment by germasch** [comment]
Side comment: Currently, gtensor synchronizes after kernels depending on whether or not NDEBUG is defined. I think we should have a separate way of controlling this, it's kinda surprising, and it may lead to bugs disappearing once one starts debugging them and turning on assertions.

**Comment by bd4** [comment]
We could call it `GTENSOR_SYNC_KERNELS`, default OFF?

**Comment by germasch** [comment]
Yup, that sounds fine. Though as I'm thinking about it, given there's `{CUDA,HIP}_LAUNCH_BLOCKING`, I'm not sure it's actually necessary for us to provide our own mechanism. Not sure about sycl.

**Comment by bd4** [comment]
I kind of like having a cross GPU backend env var for gtensor.

**Comment by bd4** [comment]
hip sync issue fixed by #194
