### ISSUE TITLE
constness of span/to_kernel types vs container types

### ISSUE THREAD

**Issue by bd4** [wdmapp/gtensor#39]
gtensor is designed to have const safe containers, in that `operator()` returns a const reference if called on a const instance. This is much like std::vector. std::span, on the other hand, does not consider the underlying data part of it's state (since the data is not copied when copying a span), and it's operator[] returns a non-const reference even if the instance is const. gtensor, like it's inspiration xtensor, uses the same semantics on view objects, even though it doesn't provide much extra protection, given that you can assign a view to a non-const and modify it that way. Unfortunately this causes problems for SYCL 2020 provisional, which requires a const kernel function.

More discussion here:
https://github.com/intel/llvm/issues/2538

**Comment by keryell** [comment]
Yes, you are right, there is the same behavior for `std::vector` but the `const`-ness does not propagate if not using `decltype (auto)`...
https://godbolt.org/z/YT5Evv

**Comment by bd4** [comment]
This paper has some good terminology: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1085r0.md

In particular, it uses ('deep' or 'shallow') as descriptors on (const, copy) to refer to whether the entity operates on / applies to just the members or to everything they point to. Span has shallow const, and copy. gtensor views currently have shallow copy but deep / logical const.

propagate_const is interesting, similar idea to what I am trying to do with the gtensor.to_kernel function when converting to views (const gtensor<T>.to_kernel -> gtensor_view<const T>):
https://en.cppreference.com/w/cpp/experimental/propagate_const

**Comment by bd4** [comment]
Some subtle behavior of const member functions:
https://godbolt.org/z/j5MTaM

basically if a const object has an object data member, it will be considered const as far as resolving const methods goes. This comes up in gtensor when a `const gview` owns a `gtensor` object (it was passed as rvalue to the view). If instead the `const gview` contains a reference to `gtensor`, which is by far the more common case, then the non-const version of the gtensor methods are called even with the `gview` itself is const.

**Comment by bd4** [comment]
What is frustrating about this is that the `gtensor` object inside the `const gview` is not const, it just has const method resolution. So this behavior is hidden from the type systems in some sense.

**Comment by bd4** [comment]
@keryell this is still being reviewed and may change, but if you are curious about our approach take a look at the PR. The final solution is... reasonably elegant (as much as TMP can be) using `delctype(auto)`, but there are some subtleties that took all week to hammer out and get it working.

**Comment by keryell** [comment]
godbolt.org/z/M7EKxG seems to work, even it is not clear to me you would expect `oref.e_` to be const or not.
Otherwise, you should push http://wg21.link/P0847 to land in C++23 to simplify your code...
